
<div style="padding-bottom:48px;" class="slider-wrapper">
    <div class="content-main ">
        <div id="home-slider" class="slides owl-carousel owl-theme">
            <div class="item" style="background-size: cover; background-repeat: no-repeat;">
                <a class="banner-link" href="#" title="Slide 1"></a>
                <img class="slide-hidden-img" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/AD_BG.jpg'); ?>"  alt="Slide 1">
            </div>
            <div class="item" style="background-size: cover; background-repeat: no-repeat;">
                <img class="slide-hidden-img" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/AD_BG2.png'); ?>" alt="Slide 2">
            </div>
            <div class="item" style="background-size: cover; background-repeat: no-repeat;">
                <img class="slide-hidden-img" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Ad3.jpg'); ?>" alt="Slide 3">
            </div>
        </div>
    </div>
</div>
