<div style="background: #E7F5FD;margin-bottom:25px;margin-top:15px;" class="medi-pocket">
    <div style="padding: 48px 0 0 0;" class="container">
        <div class="row">
            <div class="col-md-7">
                <p style="color: #111;
font-family: Montserrat !important;
padding: 0 442px 0 0;
font-size: 34px;
font-style: normal;
font-weight: 700;">Get Medizin HUB in
                    your pocket </p>
                <p style="color: #111;
font-family:Source Sans Pro;
font-size: 16px;
padding: 0 380px 0 0;
font-style: normal;
font-weight: 400;
">Easy way to get your medicine at your doorstep,
                    Download it. Now!</p>
                <div style="margin-top:20px;" class="row">
                    <div class="col-md-4">
                        <img class="" width="194px" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/playstore.png'); ?>" alt="Mobile">
                    </div>
                    <div class="col-md-4">
                        <img class="" width="194px" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Apple.jpg'); ?>" alt="Mobile">

                    </div>
                    <div class="col-md-4">
                        <div style="margin-top: -10px;" class="row">
                            <div class="col-md-6">
                                <p style="color: #111;
font-family:Source Sans Pro;
font-size: 14px;">Open Camera & Scan
                                    QR to download the
                                    My Prop AI </p>
                            </div>
                            <div class="col-md-6">
                                <img class="" width="98px" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Vector.png'); ?>" alt="Mobile">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-1"></div>
            <div class="col-md-4">
                <img class="" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Asset_1_2.png'); ?>" alt="Mobile">
            </div>
        </div>
    </div>
</div>
