<?php
/**
 * This block retrieves a category and displays its name along with product details.
 * Adjust the code based on your specific requirements.
 */

$categoryID = $this->getRequest()->getParam('id');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$mediaBaseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

$categoryName = '';
$category = $objectManager->create('Magento\Catalog\Model\Category')->load($categoryID);

if ($category->getId()) {
    $categoryName = $category->getName();
}

$categoryCollection = $block->getProductCollectionByCategories($categoryID);

$pageSize = 24; // Number of products per page
$pager = $block->getLayout()->createBlock('\Magento\Theme\Block\Html\Pager', 'custom.pager');
$pager->setAvailableLimit([$pageSize => $pageSize])
    ->setShowPerPage(true)
    ->setCollection($categoryCollection);
?>


<div style="margin-top: -30px;" class="product-list-cat">
    <div class="container">
        <div style="margin-top: 40px;" class="row">
            <p style="color: #063851; font-family: Source Sans Pro, Sans-serif; font-size: 24px; font-weight: 600;"><?php echo $categoryName; ?></p>
            <p style="color: #859ca8; font-family: Ubuntu, Sans-serif; font-size: 18px; font-weight: 400;">Get a flat 50% discount on top deals</p>

            <?php foreach ($categoryCollection as $product) : ?>
                <?php
                $productName = $product->getName();
                $productUrl = $product->getProductUrl();
                $productImage = $product->getImage();
                $productImageUrl = $mediaBaseUrl . 'catalog/product' . $productImage;
                $regularPrice = $product->getPriceInfo()->getPrice('regular_price')->getAmount()->getValue();
                $finalPrice = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();
                ?>
                <div style="margin-top: 15px;" class="col-md-3 productlist">
                    <div style="background: #f1f9fe; height: 290px !important; border-radius: 8px; padding: 10px;" class="product-slide">
                        <div style="width: 100%;text-align:center;" class="productlist-img">
                            <img style="margin: 20px 30px; height: 105px;" class="grow" width="100px" src="<?= $productImageUrl ?>" alt="<?= $productName ?>">
                        </div>
                        <div style="padding: 0 14px;" class="product-details">
                            <span style="font-size: 16px !important; font-weight: 600 !important; font-family: Source Sans Pro !important; text-decoration:none;" class="product-name">
                                <?= $productName ?><br>
                                <p style="color: var(--Input-Text, #797979); font-family: Source Sans Pro; font-size: 14px; font-style: normal; font-weight: 400; line-height: normal; margin-bottom: 2px;"><?php echo $categoryName; ?></p>
                                <span style="font-family: Source Sans Pro; font-size: 22px; font-style: normal; font-weight: 700; line-height: normal; text-decoration:none;" class="product-price">₹<?= $finalPrice ?></span>
                                <br>
                                <a href="<?= $productUrl ?>"> <button style="margin-top: 5px;width: 238px; height: 44px; padding: 10px 18px; border-radius: 8px; background: linear-gradient(94deg, #03C777 56.99%, #01A462 99.73%); color: #FFF; font-family: Source Sans Pro; font-size: 16px; font-style: normal; font-weight: 700;" class="add-to-cart-btn grow" data-product-id="<?= $product->getId() ?>">Add to Cart</button></a>
                            </span>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>

            <!-- Add pagination block -->
            <div class="col-md-12">
                <div class="productlist-pagination">
                    <?= $pager->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .productlist-pagination {
        width: 100%;
        text-align: center;
        margin-top: 30px;
    }
    .page-title-wrapper{
        display: none;
    }


    .toolbar-amount {
        display: none !important;
    }

    .pages .action.previous {
        height: 34px;
        width: 34px;
        margin-left: 0;
        margin-right: 0;
        transition: all 0.2s ease-in-out;
        -moz-transition: all 0.2s ease-in-out;
        -webkit-transition: all 0.2s ease-in-out;
        box-sizing: border-box;
        border: 1px solid #fff;
        color: #ffffff;
        background: #ffffff;
        border-radius: 0;
        -webkit-border-radius: 0;
        -moz-border-radius: 0;
        box-shadow: none;
        -moz-box-shadow: none;
        -webkit-box-shadow: none;
    }

    .pages strong.page {
        border: 1px solid #049B7E;
        box-sizing: border-box;
        color: #ffffff;
        font-weight: 600;
        height: 34px;
        line-height: 32px;
        min-width: 15px;
        padding: 0;
        text-align: center;
        width: 34px;
        border-radius: 50%;
        background: #049B7E;
    }

    .pages .action.next {
        height: 34px;
        width: 34px;
        margin-left: 0;
        margin-right: 0;
        transition: all 0.3s ease 0s;
        -moz-transition: all 0.3s ease 0s;
        -webkit-transition: all 0.3s ease 0s;
        box-sizing: border-box;
        border: 1px solid #fff !important;
        color: #333333;
        background: #ffffff;
        border-radius: 0;
        -webkit-border-radius: 0;
        -moz-border-radius: 0;
        box-shadow: none;
        -moz-box-shadow: none;
        -webkit-box-shadow: none;
    }

    .pages .action.previous:hover {
        background: #049B7E;
        border-radius: 50%;
        color: #fff;
        border: 1px solid #049B7E;
    }

    .pages .action.next:hover {
        background: #049B7E;
        border-radius: 50%;
        color: #fff;
        border: 1px solid #049B7E;
    }

    .pages a.page:hover {
        background: #049B7E;
        border-radius: 50%;
        color: #fff !important;
        border: 1px solid #049B7E;
    }

    .pages .items {
        background: #F7F9FF;
        box-shadow: 0px 4px 20px 0px rgba(0, 0, 0, 0.20);
        padding: 3px 30px;
        border-radius: 26px;
    }

    .pages a.page {
        border: 1px solid #fff;
        box-sizing: border-box;
        color: #333333;
        background: #ffffff;
        display: inline-block;
        height: 34px;
        line-height: 32px;
        min-width: 15px;
        padding: 0;
        text-align: center;
        vertical-align: top;
        width: 34px;
        transition: all 0.3s ease 0s;
        -moz-transition: all 0.3s ease 0s;
        -webkit-transition: all 0.3s ease 0s;
        border-radius: 0;
        -webkit-border-radius: 0;
        -moz-border-radius: 0;
        color: #000 !important;
    }

    .search-btn {
        position: absolute;
        margin-top: -44px;
        margin-left: 532px;
        border-radius: 88px !important;
        width: 98px;
        height: 41px;
        font-size: 16px !important;
        background: linear-gradient(94deg, #03C777 56.99%, #01A462 99.73%);
        color: #fff !important;
        font-weight: 500 !important;
        border: 1px solid #03C777 !important;
    }

    #link-login {
        font-size: 17px;
        font-weight: 600;
        color: #049B7E;
        font-family: "Source Sans Pro";
        margin-top: 12px;
    }
</style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
