<style>
    main{
        display: none !important;
    }
    #link-login {
        font-size: 17px;
        font-weight: 600;
        color: #049B7E;
        font-family: "Source Sans Pro";
        margin-top: 12px;
    }

    .search-btn {
	position: absolute;
	margin-top: -44px;
	margin-left: 532px;
	border-radius: 88px !important;
	width: 98px;
	height: 41px;
	font-size: 16px !important;
	background: linear-gradient(94deg, #03C777 56.99%, #01A462 99.73%);
	color: #fff !important;
	font-weight: 500 !important;
	border: 1px solid #03C777 !important;
}
    .online-consult{
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_ConsultOption::images/Online_consultation.png');?>);
        background-repeat: no-repeat;
        background-position: center;
    }
    .home-consult{
        background-image: url(<?= $block->getViewFileUrl('MedizinhubCore_ConsultOption::images/Online_consultation2.png');?>);
        background-repeat: no-repeat;
        background-position: center;
    }
    .online-consult p{
        color: #0A2916;
font-family: "Reem Kufi";
font-size: 20px;
font-style: normal;
font-weight: 600;
padding: 70px 68px 61px 62px;
line-height: normal;
    }
    .home-consult p{
        color: #0A2916;
font-family: "Reem Kufi";
font-size: 20px;
font-style: normal;
font-weight: 600;
padding: 70px 68px 61px 62px;
line-height: normal;
    }
    .home-consult button{
        color: #FFF;
font-family: Montserrat;
font-size: 12.176px;
font-style: normal;
font-weight: 600;
border-radius: 4.87px;
background: #063851;
padding: 5px 16px;
margin-top: -110px;
  margin-left: 60px;
  height: 32px;
  width: 100px;
    }
    .page-title-wrapper{
        display: none;
    }

    .online-consult button{
        color: #FFF;
font-family: Montserrat;
font-size: 12.176px;
font-style: normal;
font-weight: 600;
border-radius: 4.87px;
background: #124F2A;
padding: 5px 16px;
margin-top: -110px;
  margin-left: 60px;
  height: 32px;
  margin-top: -110px;
  margin-left: 60px;
  height: 32px;
  width: 100px;
  width: 100px;
    }
</style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

<div class="consult-option">
    <div class="container">
        <div class="row">
        <p style="padding: 0 70px;color: #063851;font-family: Source Sans Pro,Sans-serif;font-size: 24px;font-weight: 600;">Select option for consult</p>
            <p style="padding: 0 70px; color: #859ca8;font-family: Ubuntu,Sans-serif;font-size: 18px;font-weight: 400;">we offer a quality consult to you</p>
            <div class="col-md-2">
            </div>
            <div class="col-md-4">
                <div class="online-consult">
<p>Doctor Online <br>
Visit</p>
<a href="/confirm-order"><button>Book Now</button></a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="home-consult">
<p>Doctor Home <br>
Consult</p>
<a href="/confirm-order"><button>Book Now</button></a>
                </div>
            </div>
            <div class="col-md-2">
            </div>
        </div>
    </div>
</div>



<div style="background: #E7F5FD;margin-bottom:25px;margin-top:15px;" class="medi-pocket">
    <div style="padding: 48px 0 0 0;" class="container">
        <div class="row">
            <div class="col-md-7">
                <p style="color: #111;
font-family: Montserrat !important;
padding: 0 442px 0 0;
font-size: 34px;
font-style: normal;
font-weight: 700;">Get Medizin HUB in
                    your pocket </p>
                <p style="color: #111;
font-family:Source Sans Pro;
font-size: 16px;
padding: 0 380px 0 0;
font-style: normal;
font-weight: 400;
">Easy way to get your medicine at your doorstep,
                    Download it. Now!</p>
                <div style="margin-top:20px;" class="row">
                    <div class="col-md-4">
                        <img class="" width="194px" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/playstore.png'); ?>" alt="Mobile">
                    </div>
                    <div class="col-md-4">
                        <img class="" width="194px" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Apple.jpg'); ?>" alt="Mobile">

                    </div>
                    <div class="col-md-4">
                        <div style="margin-top: -10px;" class="row">
                            <div class="col-md-6">
                                <p style="color: #111;
font-family:Source Sans Pro;
font-size: 14px;">Open Camera & Scan
                                    QR to download the
                                    My Prop AI </p>
                            </div>
                            <div class="col-md-6">
                                <img class="" width="98px" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Vector.png'); ?>" alt="Mobile">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-1"></div>
            <div class="col-md-4">
                <img class="" src="<?= $block->getViewFileUrl('MedizinhubCore_Home::images/Asset_1_2.png'); ?>" alt="Mobile">
            </div>
        </div>
    </div>
</div>
